package syncthingrest.model.gui

import kotlinx.serialization.Serializable

/**
 * Sources:
 * - https://github.com/syncthing/syncthing/tree/master/lib/config
 * - https://github.com/syncthing/syncthing/blob/master/lib/config/guiconfiguration.go
 */
@Serializable
data class Gui(
    var debugging: Boolean = false,
    var enabled: Boolean = true,

    /**
     * REST: useTLS
     * XML: tls
     */
    var useTLS: Boolean = false,

    var address: String = "127.0.0.1:8384",
    var user: String = "",
    var password: String = "",
    var apiKey: String, // Automatically generated by SyncthingNative

    var theme: Theme = Theme.DEFAULT,

    // omitEmpty
    var insecureAdminAccess: Boolean = false,
    var insecureAllowFrameLoading: Boolean = false,
    var insecureSkipHostCheck: Boolean = false,
) {
    val bindAddress: String?
        get() {
            val split: Array<String?> =
                address.split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
            return if (split.isEmpty()) "" else split[0]
        }

    val bindPort: String?
        get() {
            val split: Array<String?> =
                address.split(":".toRegex()).dropLastWhile { it.isEmpty() }.toTypedArray()
            return if (split.size < 2) "" else split[1]
        }
}