package syncthingrest.model

import kotlinx.serialization.Serializable

@Serializable
data class Options(
    val listenAddresses: List<String>,
    val globalAnnounceServers: List<String>,
    val globalAnnounceEnabled: Boolean,
    val localAnnounceEnabled: Boolean,
    val localAnnouncePort: Int,
    val localAnnounceMCAddr: String,
    val maxSendKbps: Int,
    val maxRecvKbps: Int,
    val reconnectionIntervalS: Int,
    val relaysEnabled: Boolean,
    val relayReconnectIntervalM: Int,
    val startBrowser: Boolean,
    val natEnabled: Boolean,
    val natLeaseMinutes: Int,
    val natRenewalMinutes: Int,
    val natTimeoutSeconds: Int,
    val urAccepted: Int,
    val urSeen: Int,
    val urUniqueId: String,
    val urURL: String,
    val urPostInsecurely: Boolean,
    val urInitialDelayS: Int,
    val autoUpgradeIntervalH: Int,
    val upgradeToPreReleases: Boolean,
    val keepTemporariesH: Int,
    val cacheIgnoredFiles: Boolean,
    val progressUpdateIntervalS: Int,
    val limitBandwidthInLan: Boolean,
    val minHomeDiskFree: String, // Corresponds to Go's 'Size' type, which is a string representation
    val releasesURL: String,
    val alwaysLocalNets: List<String>,
    val overwriteRemoteDeviceNamesOnConnect: Boolean,
    val tempIndexMinBlocks: Int,
    val unackedNotificationIDs: List<String>,
    val trafficClass: Int,
    val maxFolderConcurrency: Int,
    val crURL: String,
    val crashReportingEnabled: Boolean,
    val stunKeepaliveStartS: Int,
    val stunKeepaliveMinS: Int,
    val stunServers: List<String>,
    val databaseTuning: String, // Corresponds to Go's 'Tuning' type, assuming string representation
    val maxConcurrentIncomingRequestKiB: Int,
    val announceLANAddresses: Boolean,
    val sendFullIndexOnUpgrade: Boolean,
    val featureFlags: List<String>,
    val auditEnabled: Boolean,
    val auditFile: String,
    val connectionLimitEnough: Int,
    val connectionLimitMax: Int,
    val connectionPriorityTcpLan: Int,
    val connectionPriorityQuicLan: Int,
    val connectionPriorityTcpWan: Int,
    val connectionPriorityQuicWan: Int,
    val connectionPriorityUpgradeThreshold: Int
)
